### ISSUE TITLE
Why not have Mastodon and Lemmy Redirect be in the same app?

### ISSUE THREAD

**Issue by Jaoheah** [zacharee/MastodonRedirect#18]
i was just wondering why they are seperate apps. Maybe you could just have them be in the same app, and you could rename it to Fediverse Redirect?

**Comment by zacharee** [comment]
I have a few reasons for that:

1. Mastodon Redirect alone is handling over 18,000 domains. Depending on what version and skin of Android you're running, that's enough to make Settings crash when you try to open App Info. I'm working on reducing the number while keeping most functionality, but it's always going to be a lot. Adding Lemmy Redirect's 3,000+ domains (and growing) to the mix is just going to make that problem worse. (Also, Android Studio gets pretty slow when editing the massive manifest files.)
2. I can't really think of a good way to put the selector for both into one app. UI considerations aside, Android doesn't have a great way to list your own app's deep links and categorize them (Mastodon vs. Lemmy), especially below Android 12, so I would probably have to implement my own parsing for every handled link to know where to send it.
3. Some people might use Mastodon and not Lemmy or vice-versa. Separate apps means people can choose which service they want to have handled without needing extra granular controls for deselecting/selecting domains by category (see above for why that's hard to do).

I know 15MB per app isn't exactly tiny (Jetpack Compose is responsible for most of that), but since they don't store any data aside from a few preferences, they shouldn't ever take up more than the 15MB for the app and whatever extra Android generates when optimizing installed apps.
